import { execSync } from "child_process";
import { randomUUID } from "crypto";

const apiKey = process.env.GITHUB_API_KEY;
const branchName = `suggestions-branch-${randomUUID()}`;

/**
 * Creates a new branch, commits changes, and opens a pull request.
 */
export function createPullRequest(filePath: string) {
  try {
    // Create a new branch
    execSync(`git checkout -b ${branchName}`, { stdio: "inherit" });

    // Add changes to git
    execSync(`git add ${filePath}`, { stdio: "inherit" });
    execSync(`git commit -m "Add suggestions"`, { stdio: "inherit" });

    // Push changes to GitHub
    execSync(`git push origin ${branchName}`, { stdio: "inherit" });

    // Create a pull request
    execSync(
      `gh pr create --base main --head ${branchName} --title "Suggestions" --body "This PR contains suggestions generated by the AI model."`,
      { stdio: "inherit" },
    );

    console.log("Pull request created successfully.");
  } catch (error) {
    throw new Error(`Failed to create pull request: ${error.message}`);
  }
}
