name: Playwright Tests
on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn global add yarn && yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps chromium

      - name: Run Playwright tests
        run: yarn playwright test --only-changed=origin/main

      - name: Run script and capture output
        if: always()
        id: "script"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: yarn tsx ai-helper/results_suggestions.ts

      - name: Append or replace PR description suggestion section
        if: always()
        uses: actions/github-script@v7
        env:
          output: ${{ steps.script.outputs.output }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const suggestions = fs.readFileSync('script_output.txt', 'utf8').trim();

            if (!suggestions) {
              throw new Error("No suggestions found in 'script_output.txt'.");
            }

            const currentBody = pullRequest.body || '';
            const startMarker = ':robot: Definitely not a bot! Here are some suggestions:';
            const newBody = startMarker + currentBody.substring(0, currentBody.indexOf(startMarker)) + suggestions;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: newBody,
            });

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: test-results.json
          retention-days: 30
